# Generated by Django 5.1.6 on 2025-03-06 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='expireon',
        ),
        migrations.AddField(
            model_name='iteminstance',
            name='expireon',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
