# Generated by Django 5.1.6 on 2025-03-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
