# Generated by Django 5.1.6 on 2025-03-17 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket_app', '0003_alter_iteminstance_expireon_commentreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ReadFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iteminstance',
            name='expireon',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 18, 11, 13, 40, 160308, tzinfo=datetime.timezone.utc)),
        ),
    ]
